name: Java CI with Gradle

on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ]  

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
          
      ## create application.properties
      - name: make application.properties
        if: true # branch가 develop일 때
        run: |
          # spring의 resources 경로로 이동
          cd ./src/main/resources
          touch ./application.properties

          # GitHub-Actions에서 설정한 값을 application.properties 파일에 쓰기
          echo "${{ secrets.PROPERTIES }}" > ./application.properties

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle 
        run: ./gradlew build    
        shell: bash             

      # https://github.com/docker/build-push-action
      # docker 시작
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with: 
          username: ojy9612
          password: ${{ secrets.DOCKER_PWD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .  # base folder
          file: ./Dockerfile # Dockerfile path
          platforms: linux/amd64 # m1에서는 - linux/arm64/v8
          push: true                                       # github 저장소 명으로 도커 imagename 설정 
          tags: ojy9612/${{ github.event.repository.name }} # username/imagename:tagname  tagname 생략 시 latest로 입력됨.
